export const langKeys = {
  featureTitle: "feature.title",
  joinLeaveMsgTitle: "feature.joinLeaveMsg.title",
  joinLeaveMsgDescription: "feature.joinLeaveMsg.desc",
  eventLogTitle: "feature.eventLog.title",
  eventLogDescription: "feature.eventLog.desc",
  inServerRptTitle: "feature.inServerRpt.title",
  inServerRptDescription: "feature.inServerRpt.desc",
  messageExpTitle: "feature.messageExp.title",
  messageExpDescription: "feature.messageExp.desc",
  chgVerifyLvTitle: "feature.chgVerifyLv.title",
  chgVerifyLvDescription: "feature.chgVerifyLv.desc",
  autoPublicTitle: "feature.autoPublic.title",
  autoPublicDescription: "feature.autoPublic.desc",
  autoModPlusTitle: "feature.autoModPlus.title",
  autoModPlusDescription: "feature.autoModPlus.desc",
  autoThreadTitle: "feature.autoThread.title",
  autoThreadDescription: "feature.autoThread.desc",
} as const;